import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db'; import { requireUser } from '@/lib/auth'; import { can } from '@/lib/rbac'; import { audit } from '@/lib/audit';
export async function POST(req:NextRequest){ try { const s:any=await requireUser(); if(!can(s.role,'ai_use')) return NextResponse.json({error:'Forbidden'},{status:403}); if(!s.schoolId) return NextResponse.json({error:'School context required'},{status:400}); const {message,confirm}=await req.json(); const text=String(message||'').trim(); if(!text) return NextResponse.json({error:'Message required'},{status:400}); const lower=text.toLowerCase();
 if(lower.includes('owing')||lower.includes('outstanding')){ const charges=await db.feeCharge.findMany({where:{schoolId:s.schoolId},include:{student:true,payments:{where:{status:'PAID'}}},take:500}); const rows=charges.map(c=>({student:`${c.student.firstName} ${c.student.lastName}`,studentId:c.student.studentId,charge:Number(c.amount),paid:c.payments.reduce((a,p)=>a+Number(p.amount),0)})).map(x=>({...x,balance:x.charge-x.paid})).filter(x=>x.balance>0).sort((a,b)=>b.balance-a.balance); await audit({schoolId:s.schoolId,userId:s.sub,action:'AI_QUERY',entity:'FeeCharge',metadata:{query:text}}); return NextResponse.json({type:'table',title:'Outstanding fees',data:rows}); }
 if(lower.includes('attendance')&&lower.includes('75')){ const students=await db.student.findMany({where:{schoolId:s.schoolId},include:{attendance:true},take:500}); const data=students.map(st=>{const a=st.attendance; const pct=a.length?Math.round(a.filter(x=>x.status==='PRESENT').length/a.length*100):100; return {student:`${st.firstName} ${st.lastName}`,studentId:st.studentId,attendance:`${pct}%`}}).filter(x=>parseInt(x.attendance)<75); return NextResponse.json({type:'table',title:'Students below 75% attendance',data}); }
 if(lower.startsWith('create')&&lower.includes('test')){ if(!confirm) return NextResponse.json({type:'confirmation',message:'Creating and publishing an assessment is a sensitive action. Reply with confirm=true to continue.'}); await audit({schoolId:s.schoolId,userId:s.sub,action:'AI_SENSITIVE_ACTION',entity:'Assessment',metadata:{query:text}}); return NextResponse.json({type:'message',message:'Assessment action is authorized. Connect the configured AI provider/question generator, select class, subject and marking scheme, then publish.'}); }
 if(!process.env.AI_API_KEY) return NextResponse.json({type:'message',message:'LES Intelligence is running in secure local-tool mode. Add AI_API_KEY and AI_BASE_URL to enable natural-language generation. Core school-data tools remain permission-checked.'});
 return NextResponse.json({type:'message',message:'AI provider credentials are present, but the provider adapter is intentionally isolated. Implement the adapter without granting direct database access to the model.'});
 } catch(e:any){return NextResponse.json({error:e.message},{status:401});}}
